### ISSUE TITLE
CODE ALONG III: GROUP BY() Exercise doesn't use GROUP BY

### ISSUE THREAD

**Issue by alexbarron** [learn-co-students/sql-grouping-and-sorting-readme-v-000#1]
The exercise in Code Along III for GROUP BY doesn't actually use GROUP BY.

Code:
`SELECT SUM(Cats.net_worth) 
FROM Owners 
INNER JOIN cats_owners 
ON Owners.id = cats_owners.owner_id 
JOIN Cats ON cats_owners.cat_id = Cats.id 
WHERE cats_owners.owner_id = 2;`

Can this example exercise be re-written to make it more clear how to use GROUP BY?

**Comment by gj** [comment]
cc: @pletcher

**Comment by genericlady** [comment]
@Lukeghenco @aturkewi 
Hey, next week maybe we should tackle this in a PR. What do you think?

[stack overflow example 1](http://stackoverflow.com/questions/2404565/sql-server-difference-between-partition-by-and-group-by)
[stack overflow example 2](http://stackoverflow.com/questions/11986321/what-does-group-by-do-exactly)

**Comment by aturkewi** [comment]
Thanks for raising! I'm going to close this out though so that we can track the issue on the canonical copy of the lab rather than this specific deploy of the lab. (You can always get to the canonical copy by using the raise issue button on Learn.)

https://github.com/learn-co-curriculum/sql-grouping-and-sorting-readme/issues/15
